# fish completion for copilot
# Generated by `copilot completion fish`. Do not edit by hand.

function __copilot_at_path --description 'copilot: true when the resolved subcommand path equals the given tokens'
    set -l tokens (commandline -poc)
    set -l required '--add-dir' '--add-github-mcp-tool' '--add-github-mcp-toolset' '--additional-mcp-config' '--agent' '--attachment' '--context' '--disable-mcp-server' '--effort' '--env' '--extension-sdk-path' '--header' '--host' '--interactive' '--kind' '--log-dir' '--log-level' '--max-ai-credits' '--max-autopilot-continues' '--mode' '--model' '--name' '--output-format' '--plugin-dir' '--prompt' '--reasoning-effort' '--scope' '--session-id' '--stream' '--timeout' '--tools' '--transport' '-C' '-i' '-n' '-p'
    set -l optional '--bash-env' '--connect' '--mouse' '--resume' '--share' '-r'
    set -l variadic '--allow-tool' '--allow-url' '--available-tools' '--deny-tool' '--deny-url' '--excluded-tools' '--secret-env-vars'
    set -l known 'login' 'help' 'init' 'update' 'version' 'plugin' 'plugin install' 'plugin uninstall' 'plugin update' 'plugin list' 'plugin marketplace' 'plugin marketplace add' 'plugin marketplace remove' 'plugin marketplace list' 'plugin marketplace browse' 'plugin marketplace update' 'mcp' 'mcp list' 'mcp get' 'mcp add' 'mcp remove' 'plugins' 'plugins list' 'plugins enable' 'plugins disable' 'plugins remove' 'plugins rm' 'plugins install' 'plugins add' 'plugins update' 'plugins marketplace' 'plugins marketplace list' 'plugins marketplace ls' 'plugins marketplace add' 'plugins marketplace remove' 'plugins marketplace rm' 'plugins marketplace browse' 'plugins marketplace update' 'plugins marketplace refresh' 'plugins marketplaces' 'plugins marketplaces list' 'plugins marketplaces ls' 'plugins marketplaces add' 'plugins marketplaces remove' 'plugins marketplaces rm' 'plugins marketplaces browse' 'plugins marketplaces update' 'plugins marketplaces refresh' 'skill' 'skill list' 'skill add' 'skill remove' 'completion'

    set -l path
    set -l mode none
    set -l n (count $tokens)
    set -l i 2
    while test $i -le $n
        set -l w $tokens[$i]
        if test "$w" = '--'
            break
        end
        if test "$mode" = required
            set mode none
            set i (math $i + 1)
            continue
        end
        # The path this token would extend to. The resolved path is not reassigned
        # until after both uses below, so one computation serves the mid-consumption
        # check and the subcommand check.
        set -l candidate (string join ' ' -- $path $w)
        if test "$mode" = optional; or test "$mode" = variadic
            if string match -q -- '-*' $w; or contains -- $candidate $known
                set mode none
            else
                if test "$mode" = optional
                    set mode none
                end
                set i (math $i + 1)
                continue
            end
        end
        if string match -q -- '--*=*' $w
            # --flag=value form: value is attached, so no token to skip.
        else if string match -q -- '-*' $w
            if contains -- $w $required
                set mode required
            else if contains -- $w $optional
                set mode optional
            else if contains -- $w $variadic
                set mode variadic
            end
        else
            if contains -- $candidate $known
                set path $path $w
            end
        end
        set i (math $i + 1)
    end

    # A value-taking flag left mid-consumption -- any of required/optional/variadic left with no
    # value yet, or a variadic still open (e.g. `copilot --prompt ` or `copilot plugin --tags foo `)
    # -- means the next token may be the flag's value, not a subcommand. Only `ready` callers
    # (subcommand/positional registrations) suppress in that state, matching the bash/zsh walkers;
    # `any` callers (a flag's own value registration) still match so the flag can offer its value
    # choices while consuming.
    if test "$argv[1]" = ready; and test "$mode" != none
        return 1
    end
    set -l current (string join ' ' -- $path)
    set -l target (string join ' ' -- $argv[2..-1])
    test "$current" = "$target"
end

complete -c copilot -n '__copilot_at_path ready' -f -a 'login' -d 'Authenticate with Copilot'
complete -c copilot -n '__copilot_at_path ready' -f -a 'help' -d 'Display help information'
complete -c copilot -n '__copilot_at_path ready' -f -a 'init' -d 'Initialize Copilot instructions'
complete -c copilot -n '__copilot_at_path ready' -f -a 'update' -d 'Download the latest version'
complete -c copilot -n '__copilot_at_path ready' -f -a 'version' -d 'Display version information'
complete -c copilot -n '__copilot_at_path ready' -f -a 'plugin' -d 'Manage plugins'
complete -c copilot -n '__copilot_at_path ready' -f -a 'mcp' -d 'Manage MCP servers'
complete -c copilot -n '__copilot_at_path ready' -f -a 'plugins' -d 'Inspect configured plugins across kinds'
complete -c copilot -n '__copilot_at_path ready' -f -a 'skill' -d 'Manage skills'
complete -c copilot -n '__copilot_at_path ready' -f -a 'completion' -d 'Generate a shell completion script'
complete -c copilot -l version -s v -f -d 'show version information'
complete -c copilot -l interactive -s i -r -d 'Start interactive mode and automatically execute this prompt'
complete -c copilot -l prompt -s p -r -d 'Execute a prompt in non-interactive mode (exits after completion)'
complete -c copilot -l silent -s s -f -d 'Output only the agent response (no stats), useful for scripting with -p'
complete -c copilot -l enable-memory -f -d 'Enable memory in prompt mode (disabled by default)'
complete -c copilot -l model -r -f -a 'auto claude-sonnet-5 claude-fable-5 claude-opus-5 claude-opus-4.8 claude-opus-4.8-fast claude-opus-4.7 claude-sonnet-4.6 claude-opus-4.6 claude-sonnet-4.5 claude-opus-4.5 claude-haiku-4.5 gpt-5.6-sol gpt-5.6-terra gpt-5.6-luna gpt-5.5 gpt-5.4 gpt-5.4-mini gpt-5.3-codex gpt-5-mini mai-code-1-flash-picker gemini-3.7-flash gemini-3.6-flash gemini-3.5-flash gemini-3.1-pro-preview grok-4.5 kimi-k3 kimi-k2.7-code'
complete -c copilot -l model -r -f -d 'Set the AI model to use (use \'auto\' to let Copilot pick automatically)'
complete -c copilot -l effort -l reasoning-effort -r -f -a 'none minimal low medium high xhigh max'
complete -c copilot -l effort -l reasoning-effort -r -f -d 'Set the reasoning effort level'
complete -c copilot -l context -r -f -a 'default long_context'
complete -c copilot -l context -r -f -d 'Set the context window tier (overrides persisted setting)'
complete -c copilot -l enable-reasoning-summaries -f -d 'Request reasoning summaries for OpenAI models'
complete -c copilot -l agent -r -d 'Specify a custom agent to use'
complete -c copilot -l resume -s r -r -d 'Resume from a previous session (optionally specify existing session ID, task ID, ID prefix, or name; name matching is exact, case-insensitive)'
complete -c copilot -l continue -f -d 'Resume the most recent session'
complete -c copilot -l name -s n -r -d 'Set a name for the new session'
complete -c copilot -l session-id -r -d 'Resume an existing session or task by ID, or set the UUID for a new session'
complete -c copilot -l connect -r -d 'Connect directly to a remote session (optionally specify session ID or task ID)'
complete -c copilot -l allow-all-tools -f -d 'Allow all tools to run automatically without confirmation; required for non-interactive mode'
complete -c copilot -l allow-all-paths -f -d 'Disable file path verification and allow access to any path'
complete -c copilot -l disallow-temp-dir -f -d 'Prevent automatic access to the system temporary directory'
complete -c copilot -l no-custom-instructions -f -d 'Disable loading of custom instructions from AGENTS.md and related files'
complete -c copilot -l no-auto-update -f -d 'Disable downloading CLI update automatically (disabled by default in CI environments)'
complete -c copilot -l no-ask-user -f -d 'Disable the ask_user tool (agent works autonomously without asking questions)'
complete -c copilot -l banner -f -d 'Show the startup banner'
complete -c copilot -l no-color -f -d 'Disable all color output'
complete -c copilot -l screen-reader -f -d 'Enable screen reader optimizations'
complete -c copilot -l plain-diff -f -d 'Disable rich diff rendering (syntax highlighting via diff tool specified by git config)'
complete -c copilot -s C -r -d 'Change working directory before doing anything else'
complete -c copilot -l log-dir -r -d 'Set log file directory (default: ~/.copilot/logs/)'
complete -c copilot -l extension-sdk-path -r -d 'Override the bundled @github/copilot-sdk injected into extension subprocesses with a local `copilot-sdk/` folder. Invalid paths fall back to the bundled SDK.'
complete -c copilot -l log-level -r -f -a 'none error warning info debug all default'
complete -c copilot -l log-level -r -f -d 'Set the log level'
complete -c copilot -l stream -r -f -a 'on off'
complete -c copilot -l stream -r -f -d 'Enable or disable streaming mode'
complete -c copilot -l output-format -r -f -a 'text json'
complete -c copilot -l output-format -r -f -d 'Output format: \'text\' (default) or \'json\' (JSONL, one JSON object per line)'
complete -c copilot -l share -r -d 'Share session to markdown file after completion in non-interactive mode (default: ./copilot-session-<id>.md)'
complete -c copilot -l share-gist -f -d 'Share session to a secret GitHub gist after completion in non-interactive mode'
complete -c copilot -l add-dir -r -d 'Add a directory to the allowed list for file access (can be used multiple times)'
complete -c copilot -l attachment -r -d 'Attach a file (image or native document) to the initial prompt; only valid in non-interactive mode (can be used multiple times)'
complete -c copilot -l disable-mcp-server -r -d 'Disable a specific MCP server (can be used multiple times)'
complete -c copilot -l disable-builtin-mcps -f -d 'Disable all built-in MCP servers (currently: github-mcp-server)'
complete -c copilot -l enable-all-github-mcp-tools -f -d 'Enable all GitHub MCP server tools instead of the default CLI subset. Overrides --add-github-mcp-toolset and --add-github-mcp-tool options.'
complete -c copilot -l add-github-mcp-toolset -r -d 'Add a toolset to enable for the GitHub MCP server instead of the default CLI subset (can be used multiple times). Use "all" for all toolsets.'
complete -c copilot -l add-github-mcp-tool -r -d 'Add a tool to enable for the GitHub MCP server instead of the default CLI subset (can be used multiple times). Use "*" for all tools.'
complete -c copilot -l plugin-dir -r -d 'Load a plugin from a local directory (can be used multiple times)'
complete -c copilot -l additional-mcp-config -r -d 'Additional MCP servers configuration as JSON string or file path (prefix with @) (can be used multiple times; augments config from ~/.copilot/mcp-config.json for this session)'
complete -c copilot -l allow-all-mcp-server-instructions -f -d 'Include initialization instructions from all MCP servers in the system prompt instead of only allowlisted servers'
complete -c copilot -l allow-tool -r -d 'Tools the CLI has permission to use; will not prompt for permission'
complete -c copilot -l deny-tool -r -d 'Tools the CLI does not have permission to use; will not prompt for permission'
complete -c copilot -l available-tools -r -d 'Only these tools will be available to the model'
complete -c copilot -l excluded-tools -r -d 'These tools will not be available to the model'
complete -c copilot -l secret-env-vars -r -d 'Environment variable names whose values are stripped from shell and MCP server environments and redacted from output (e.g., --secret-env-vars=MY_KEY,OTHER_KEY)'
complete -c copilot -l allow-url -r -d 'Allow access to specific URLs or domains'
complete -c copilot -l deny-url -r -d 'Deny access to specific URLs or domains, takes precedence over --allow-url'
complete -c copilot -l allow-all-urls -f -d 'Allow access to all URLs without confirmation'
complete -c copilot -l allow-all -f -d 'Enable all permissions (equivalent to --allow-all-tools --allow-all-paths --allow-all-urls)'
complete -c copilot -l yolo -f -d 'Enable all permissions (equivalent to --allow-all-tools --allow-all-paths --allow-all-urls)'
complete -c copilot -l max-autopilot-continues -r -d 'Maximum number of continuation messages in autopilot mode'
complete -c copilot -l mode -r -f -a 'interactive plan autopilot'
complete -c copilot -l mode -r -f -d 'Set the initial agent mode'
complete -c copilot -l autopilot -f -d 'Start in autopilot mode'
complete -c copilot -l plan -f -d 'Start in plan mode (combine with --mode autopilot to auto-approve the plan and implement it autonomously)'
complete -c copilot -l experimental -f -d 'Enable experimental features'
complete -c copilot -l no-experimental -f -d 'Disable experimental features'
complete -c copilot -l bash-env -r -d 'Enable BASH_ENV support for bash shells (on|off)'
complete -c copilot -l no-bash-env -f -d 'Disable BASH_ENV support for bash shells'
complete -c copilot -l mouse -r -d 'Enable mouse support in alt screen mode (on|off)'
complete -c copilot -l no-mouse -f -d 'Disable mouse support in alt screen mode'
complete -c copilot -l acp -f -d 'Start as Agent Client Protocol server'
complete -c copilot -l remote -f -d 'Enable remote control of your session from GitHub web and mobile'
complete -c copilot -l no-remote -f -d 'Disable remote control of your session from GitHub web and mobile'
complete -c copilot -l remote-export -f -d 'Export your session to GitHub web and mobile (read-only; does not enable remote control)'
complete -c copilot -l no-remote-export -f -d 'Disable exporting your session to GitHub web and mobile (also disables remote control)'
complete -c copilot -l max-ai-credits -r -d 'Set max AI credits for this session'
complete -c copilot -n '__copilot_at_path any login' -l host -r -d 'GitHub host URL (default: https://github.com)'
complete -c copilot -n '__copilot_at_path any login' -l device-code -f -d 'Authenticate using the OAuth device code flow (default in remote or headless environments)'
complete -c copilot -n '__copilot_at_path any login' -l web-flow -f -d 'Authenticate using the browser (web) flow (default on local desktops)'
complete -c copilot -n '__copilot_at_path ready update' -f -a 'stable prerelease'
complete -c copilot -n '__copilot_at_path ready plugin' -f -a 'install' -d 'Install a plugin'
complete -c copilot -n '__copilot_at_path ready plugin' -f -a 'uninstall' -d 'Uninstall a plugin'
complete -c copilot -n '__copilot_at_path ready plugin' -f -a 'update' -d 'Update a plugin'
complete -c copilot -n '__copilot_at_path ready plugin' -f -a 'list' -d 'List installed and --plugin-dir plugins'
complete -c copilot -n '__copilot_at_path ready plugin' -f -a 'marketplace' -d 'Manage plugin marketplaces'
complete -c copilot -n '__copilot_at_path any plugin update' -l all -f -d 'Update all installed plugins'
complete -c copilot -n '__copilot_at_path ready plugin marketplace' -f -a 'add' -d 'Add a marketplace'
complete -c copilot -n '__copilot_at_path ready plugin marketplace' -f -a 'remove' -d 'Remove a marketplace'
complete -c copilot -n '__copilot_at_path ready plugin marketplace' -f -a 'list' -d 'List registered marketplaces'
complete -c copilot -n '__copilot_at_path ready plugin marketplace' -f -a 'browse' -d 'Browse plugins in a marketplace'
complete -c copilot -n '__copilot_at_path ready plugin marketplace' -f -a 'update' -d 'Update marketplace plugin catalogs'
complete -c copilot -n '__copilot_at_path any plugin marketplace remove' -l force -s f -f -d 'Force removal even if plugins are installed'
complete -c copilot -n '__copilot_at_path ready mcp' -f -a 'list' -d 'List configured MCP servers'
complete -c copilot -n '__copilot_at_path ready mcp' -f -a 'get' -d 'Show server details'
complete -c copilot -n '__copilot_at_path ready mcp' -f -a 'add' -d 'Add an MCP server'
complete -c copilot -n '__copilot_at_path ready mcp' -f -a 'remove' -d 'Remove an MCP server'
complete -c copilot -n '__copilot_at_path any mcp list' -l json -f -d 'Output as JSON'
complete -c copilot -n '__copilot_at_path any mcp get' -l json -f -d 'Output as JSON'
complete -c copilot -n '__copilot_at_path any mcp get' -l show-secrets -f -d 'Show full environment variable and header values (masked by default)'
complete -c copilot -n '__copilot_at_path any mcp add' -l transport -r -f -a 'stdio http sse'
complete -c copilot -n '__copilot_at_path any mcp add' -l transport -r -f -d 'Server transport'
complete -c copilot -n '__copilot_at_path any mcp add' -l env -r -d 'Environment variable (KEY=VALUE, can be repeated)'
complete -c copilot -n '__copilot_at_path any mcp add' -l header -r -d 'HTTP header for remote servers, can be repeated'
complete -c copilot -n '__copilot_at_path any mcp add' -l tools -r -d 'Tool filter: "*" for all, comma-separated list, or "" for none'
complete -c copilot -n '__copilot_at_path any mcp add' -l timeout -r -d 'Timeout in milliseconds'
complete -c copilot -n '__copilot_at_path any mcp add' -l json -f -d 'Output added config as JSON'
complete -c copilot -n '__copilot_at_path any mcp add' -l show-secrets -f -d 'Show full environment variable and header values in output, masked by default'
complete -c copilot -n '__copilot_at_path ready plugins' -f -a 'list' -d 'List configured plugins across kinds'
complete -c copilot -n '__copilot_at_path ready plugins' -f -a 'enable' -d 'Enable a configured tool'
complete -c copilot -n '__copilot_at_path ready plugins' -f -a 'disable' -d 'Disable a configured tool'
complete -c copilot -n '__copilot_at_path ready plugins' -f -a 'remove' -d 'Remove an installed tool'
complete -c copilot -n '__copilot_at_path ready plugins' -f -a 'rm' -d 'Remove an installed tool'
complete -c copilot -n '__copilot_at_path ready plugins' -f -a 'install' -d 'Install a new tool'
complete -c copilot -n '__copilot_at_path ready plugins' -f -a 'add' -d 'Install a new tool'
complete -c copilot -n '__copilot_at_path ready plugins' -f -a 'update' -d 'Update a plugin'
complete -c copilot -n '__copilot_at_path ready plugins' -f -a 'marketplace' -d 'Manage plugin marketplaces'
complete -c copilot -n '__copilot_at_path ready plugins' -f -a 'marketplaces' -d 'Manage plugin marketplaces'
complete -c copilot -n '__copilot_at_path any plugins list' -l kind -r -d 'Filter by kind. Repeatable or comma-separated. Supported: plugin, mcp, skill, instruction, lsp.'
complete -c copilot -n '__copilot_at_path any plugins list' -l scope -r -d 'Filter by scope. Repeatable or comma-separated. Supported: user, repository, working-directory, organization, plugin, builtin, unknown.'
complete -c copilot -n '__copilot_at_path any plugins list' -l json -f -d 'Emit machine-readable JSON instead of grouped text'
complete -c copilot -n '__copilot_at_path any plugins enable' -l plugin -f -d 'Target a plugin (default)'
complete -c copilot -n '__copilot_at_path any plugins enable' -l mcp -f -d 'Target an MCP server'
complete -c copilot -n '__copilot_at_path any plugins enable' -l skill -f -d 'Target a skill'
complete -c copilot -n '__copilot_at_path any plugins disable' -l plugin -f -d 'Target a plugin (default)'
complete -c copilot -n '__copilot_at_path any plugins disable' -l mcp -f -d 'Target an MCP server'
complete -c copilot -n '__copilot_at_path any plugins disable' -l skill -f -d 'Target a skill'
complete -c copilot -n '__copilot_at_path any plugins remove' -l plugin -f -d 'Remove a plugin (default)'
complete -c copilot -n '__copilot_at_path any plugins remove' -l mcp -f -d 'Remove an MCP server'
complete -c copilot -n '__copilot_at_path any plugins remove' -l skill -f -d 'Remove a personal or project skill'
complete -c copilot -n '__copilot_at_path any plugins rm' -l plugin -f -d 'Remove a plugin (default)'
complete -c copilot -n '__copilot_at_path any plugins rm' -l mcp -f -d 'Remove an MCP server'
complete -c copilot -n '__copilot_at_path any plugins rm' -l skill -f -d 'Remove a personal or project skill'
complete -c copilot -n '__copilot_at_path any plugins install' -l plugin -f -d 'Install a plugin (default)'
complete -c copilot -n '__copilot_at_path any plugins install' -l skill -f -d 'Install a skill from a local path or URL'
complete -c copilot -n '__copilot_at_path any plugins install' -l mcp -f -d 'Install an MCP server (not supported here — see below)'
complete -c copilot -n '__copilot_at_path any plugins install' -l scope -r -f -a 'user project'
complete -c copilot -n '__copilot_at_path any plugins install' -l scope -r -f -d 'Install target for a file/URL --skill: user (default) or project'
complete -c copilot -n '__copilot_at_path any plugins add' -l plugin -f -d 'Install a plugin (default)'
complete -c copilot -n '__copilot_at_path any plugins add' -l skill -f -d 'Install a skill from a local path or URL'
complete -c copilot -n '__copilot_at_path any plugins add' -l mcp -f -d 'Install an MCP server (not supported here — see below)'
complete -c copilot -n '__copilot_at_path any plugins add' -l scope -r -f -a 'user project'
complete -c copilot -n '__copilot_at_path any plugins add' -l scope -r -f -d 'Install target for a file/URL --skill: user (default) or project'
complete -c copilot -n '__copilot_at_path any plugins update' -l all -f -d 'Update all installed plugins'
complete -c copilot -n '__copilot_at_path ready plugins marketplace' -f -a 'list' -d 'List registered plugin marketplaces'
complete -c copilot -n '__copilot_at_path ready plugins marketplace' -f -a 'ls' -d 'List registered plugin marketplaces'
complete -c copilot -n '__copilot_at_path ready plugins marketplace' -f -a 'add' -d 'Add a plugin marketplace'
complete -c copilot -n '__copilot_at_path ready plugins marketplace' -f -a 'remove' -d 'Remove a plugin marketplace'
complete -c copilot -n '__copilot_at_path ready plugins marketplace' -f -a 'rm' -d 'Remove a plugin marketplace'
complete -c copilot -n '__copilot_at_path ready plugins marketplace' -f -a 'browse' -d 'Browse plugins in a marketplace'
complete -c copilot -n '__copilot_at_path ready plugins marketplace' -f -a 'update' -d 'Refresh marketplace plugin catalogs'
complete -c copilot -n '__copilot_at_path ready plugins marketplace' -f -a 'refresh' -d 'Refresh marketplace plugin catalogs'
complete -c copilot -n '__copilot_at_path any plugins marketplace list' -l json -f -d 'Emit machine-readable JSON instead of grouped text'
complete -c copilot -n '__copilot_at_path any plugins marketplace ls' -l json -f -d 'Emit machine-readable JSON instead of grouped text'
complete -c copilot -n '__copilot_at_path any plugins marketplace remove' -l force -f -d 'Also uninstall every plugin sourced from this marketplace'
complete -c copilot -n '__copilot_at_path any plugins marketplace rm' -l force -f -d 'Also uninstall every plugin sourced from this marketplace'
complete -c copilot -n '__copilot_at_path any plugins marketplace browse' -l json -f -d 'Emit machine-readable JSON instead of grouped text'
complete -c copilot -n '__copilot_at_path ready plugins marketplaces' -f -a 'list' -d 'List registered plugin marketplaces'
complete -c copilot -n '__copilot_at_path ready plugins marketplaces' -f -a 'ls' -d 'List registered plugin marketplaces'
complete -c copilot -n '__copilot_at_path ready plugins marketplaces' -f -a 'add' -d 'Add a plugin marketplace'
complete -c copilot -n '__copilot_at_path ready plugins marketplaces' -f -a 'remove' -d 'Remove a plugin marketplace'
complete -c copilot -n '__copilot_at_path ready plugins marketplaces' -f -a 'rm' -d 'Remove a plugin marketplace'
complete -c copilot -n '__copilot_at_path ready plugins marketplaces' -f -a 'browse' -d 'Browse plugins in a marketplace'
complete -c copilot -n '__copilot_at_path ready plugins marketplaces' -f -a 'update' -d 'Refresh marketplace plugin catalogs'
complete -c copilot -n '__copilot_at_path ready plugins marketplaces' -f -a 'refresh' -d 'Refresh marketplace plugin catalogs'
complete -c copilot -n '__copilot_at_path any plugins marketplaces list' -l json -f -d 'Emit machine-readable JSON instead of grouped text'
complete -c copilot -n '__copilot_at_path any plugins marketplaces ls' -l json -f -d 'Emit machine-readable JSON instead of grouped text'
complete -c copilot -n '__copilot_at_path any plugins marketplaces remove' -l force -f -d 'Also uninstall every plugin sourced from this marketplace'
complete -c copilot -n '__copilot_at_path any plugins marketplaces rm' -l force -f -d 'Also uninstall every plugin sourced from this marketplace'
complete -c copilot -n '__copilot_at_path any plugins marketplaces browse' -l json -f -d 'Emit machine-readable JSON instead of grouped text'
complete -c copilot -n '__copilot_at_path ready skill' -f -a 'list' -d 'List available skills'
complete -c copilot -n '__copilot_at_path ready skill' -f -a 'add' -d 'Add a skill from a file, URL, or directory'
complete -c copilot -n '__copilot_at_path ready skill' -f -a 'remove' -d 'Remove a skill or custom skill directory'
complete -c copilot -n '__copilot_at_path any skill list' -l json -f -d 'Output as JSON'
complete -c copilot -n '__copilot_at_path any skill add' -l project -f -d 'Install the skill into the project\'s .github/skills directory'
complete -c copilot -n '__copilot_at_path ready completion' -f -a 'bash zsh fish'
