###############################################################################
# Key bindings                                                                #
###############################################################################

# Allows us to use C-a a <command> to send commands to a TMUX session inside
# another TMUX session
bind-key a send-prefix

# Set Ctrl-a as the default prefix
set-option -g prefix C-a

# Windows
bind w kill-window
# Note: that the -n means we can ignore the ctrl-a prefix
bind -n S-Left  previous-window
bind -n S-Right next-window

# Panes
bind - split-window -v               # Horizontal
bind / split-window -h               # Vertical
bind k kill-pane -a                  # Kill all panes except for the current one
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
