################################## TERM REGION #################################

# utf8 is on
setw -q -g utf8 on

# Fix colors and enable true color support and italics
set -g default-terminal "tmux-256color"
# tell Tmux that outside terminal supports true color
set -ga terminal-overrides ",alacritty:RGB"

# Increase scrollback buffer size
set -g history-limit 50000

# Set only on OS X where it's required
set -g default-command "reattach-to-user-namespace -l $SHELL"

# Emacs key bindings in tmux command prompt (prefix + :) are better than
# vi keys, even for vim users
set -g status-keys emacs

# Focus events enabled for terminals that support them
set -g focus-events on

# Use the mouse
set -g mouse on

################################ KEYBOARD REGION ###############################

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
# Although a larger value may be required in remote connections
set -s escape-time 0

## sticky time after repeated commands
set -sg repeat-time 500

# Set quick response times
set -sg escape-time 1

# Allow copy and pasting from Tmux
set-option -g default-command "reattach-to-user-namespace -l $SHELL"

################################# STATUS REGION ################################

# refresh 'status-left' and 'status-right' more often
set -g status-interval 5

################################# WINDOW REGION ################################

# Start numbering at 1 for windows and panes
set -g base-index 1
setw -g pane-base-index 1

# Automatically rename windows based on the application within
setw -g automatic-rename on

# Renumber windows if others are closed
set -g renumber-windows on

# Use titles in tabs
set -g set-titles on

# super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

################################ DISPLAY REGION ################################

set -g display-panes-time 1000

# Tmux messages are displayed for 3 seconds
set -g display-time 3000

