color_bg="#1e1e1e"
color_fg="#aab2bf"
color_green="#98c379"
color_yellow="#e5c07b"
color_red="#e06c75"
color_blue="#61afef"
color_purple="#c678dd"
color_gray="#696C77"
color_selection="#3e4452"

source "$tmux_conf_dir/skin_shared.conf"