################################## SET COLORS ##################################

text_normal=$color_gray
text_highlight=$color_green
text_emphasise=$color_purple
text_red=$color_red
text_green=$color_green
text_yellow=$color_yellow

################################## SET OPTIONS #################################

set -g status-justify "left"
set -g status-left-length "100"
set -g status "on"
set -g status-right-length "160"
set -g status-right-style none
set -g message-style bg=$color_green,fg=$color_bg
set -g status-style none
set -g pane-border-style bg=default,fg=$color_bg
set -g pane-active-border-style bg=default,fg=$color_fg
set -g status-left-style none
setw -g window-status-style bg=default,fg=$color_bg,none
setw -g window-status-current-style bg=default,fg=$color_bg
setw -g window-status-activity-style fg=$color_green,none
setw -g window-status-separator ""
set-window-option -g mode-style bg=$color_selection,fg=$color_fg
set -g @prefix_highlight_bg $color_blue # blue
set -g @prefix_highlight_fg $color_bg # white / bg

# tmux-online-status
set -g @online_icon ""
set -g @offline_icon "#[fg=$color_red]"

# tmux-pomodoro
set -g @pomodoro_on " #[fg=$text_red] "
set -g @pomodoro_complete " #[fg=$text_green] "


################################## STATUSLINE ##################################

set -g status-left "#{prefix_highlight} #[fg=$text_emphasise,bold] #S"
set -g status-right "#(battery -a -p -t -g '$text_green' -m '$text_yellow' -w '$text_red') #{pomodoro_status}#[fg=$text_normal]| #{online_status}  #[fg=$text_normal]%R"
setw -g window-status-format "#[fg=$text_normal,nobold,nounderscore,noitalics] #[fg=$text_normal] #I #W #[fg=$text_normal,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=$text_normal,nobold,nounderscore,noitalics] #[fg=$text_highlight] #I #W #[fg=$text_normal,nobold,nounderscore,noitalics]"