require("utils")
require("config.options")

require("plugins.deps")
require("plugins.lsp")
require("plugins.tree-sitter")
require("plugins.ui")
require("plugins.colorscheme")
require("plugins.editor")
require("plugins.coding")

require("config.keymaps")
require("config.autocmds")
require("config.commands")
require("config.functions")
